apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrouteudps.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteUDP
    plural: ingressrouteudps
    singular: ingressrouteudp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsstores.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSStore
    plural: tlsstores
    singular: tlsstore
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: CustomResourceDefinition
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: traefik2
    k8s.scw.cloud/object: IngressRoute
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  entryPoints:
    - traefik
  routes:
  - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
