apiVersion: v2
name: scaleway-csi
description: A Helm chart for the Scaleway CSI plugin
type: application
version: 0.2.1
appVersion: "v0.3.4"
sources:
  - https://github.com/scaleway/scaleway-csi
home: https://github.com/scaleway/scaleway-csi
keywords:
  - scaleway
  - csi
  - pvc
kubeVersion: ">= 1.25.0"
