{{- if and .Values.controller.enabled (not .Values.controller.scaleway.existingSecretName) }}
{{- $_ := required "SCW_DEFAULT_REGION must be set in values" .Values.controller.scaleway.env.SCW_DEFAULT_REGION }}
{{- $_ := required "SCW_DEFAULT_ZONE must be set in values" .Values.controller.scaleway.env.SCW_DEFAULT_ZONE }}
{{- $_ := required "SCW_DEFAULT_PROJECT_ID must be set in values" .Values.controller.scaleway.env.SCW_DEFAULT_PROJECT_ID }}
{{- $_ := required "SCW_ACCESS_KEY must be set in values" .Values.controller.scaleway.env.SCW_ACCESS_KEY }}
{{- $_ := required "SCW_SECRET_KEY must be set in values" .Values.controller.scaleway.env.SCW_SECRET_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-filestorage-csi.fullname" . }}-secret
  labels:
    {{- include "scaleway-filestorage-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.controller.scaleway.env }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
