{{- range .Values.storageClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "scaleway-csi.labels" $ | nindent 4 }}
  annotations:
  {{- if .default }}
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.scaleway.com
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ .volumeBindingMode }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
parameters:
{{- with .parameters }}
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
