{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-cloud-controller-manager.secretName" . }}
  labels:
    {{- include "scaleway-cloud-controller-manager.labels" . | nindent 4 }}
type: Opaque
data:
  SCW_ACCESS_KEY: {{ .Values.scaleway.access_key | base64 }}
  SCW_SECRET_KEY: {{ .Values.scaleway.secret_key | base64 }}
  # Project ID could also be an Organization ID
  SCW_DEFAULT_PROJECT_ID: {{ .Values.scaleway.default_project_id | base64 }}
  # Region is where your loadbalancer will be created, ex: fr-par, nl-ams
  SCW_DEFAULT_REGION: {{ .Values.scaleway.default_region | base64 }}
{{- end }}