nameOverride: ""

serviceAccount:
  annotations: {}

pod:
  annotations: {}
  priorityClassName: ""
  image:
    repository: scaleway/scaleway-secrets-store-csi
    # Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/os: linux
  affinity: {}
  tolerations: []

provider:
  debug: false
  scaleway:
    apiURL: "https://api.scaleway.com"
    insecure: false
    defaultOrganizationID:
    defaultProjectID:
    accessKey:
      secretKeyRef:
        name:
        key: accessKey
    secretKey:
      secretKeyRef:
        name:
        key: secretKey
