{{- if and .Values.controller.enabled .Values.controller.attacher.enabled }}
# Sync from https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scaleway-csi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scaleway-csi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "scaleway-csi.fullname" . }}-attacher
  apiGroup: rbac.authorization.k8s.io
{{- end }}
