{{- if and .Values.controller.enabled .Values.controller.webhook.enabled }}
# Sync from https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-webhook
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["groupsnapshot.storage.k8s.io"]
    resources: ["volumegroupsnapshotclasses"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-webhook
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scaleway-csi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "scaleway-csi.fullname" . }}-webhook
  apiGroup: rbac.authorization.k8s.io
{{- end }}
