{{- if and .Values.controller.enabled (not .Values.controller.scaleway.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-secret
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.controller.scaleway.env }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
