{{- if and .Values.controller.enabled .Values.controller.webhook.enabled }}
{{- $ca := genCA "scaleway-csi-webhook-ca" 365 }}
{{- $san := printf "%s-snapshot-validation.%s.svc" (include "scaleway-csi.fullname" .) .Release.Namespace }}
{{- $dbtlscert := genSignedCert "scaleway-csi-webhook" nil (list $san) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-webhook
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $dbtlscert.Cert | b64enc | quote }}
  tls.key: {{ $dbtlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation-webhook.snapshot.storage.k8s.io"
webhooks:
- name: "validation-webhook.snapshot.storage.k8s.io"
  rules:
  - apiGroups:   ["snapshot.storage.k8s.io"]
    apiVersions: ["v1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses"]
    scope:       "*"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace}}
      name: {{ include "scaleway-csi.fullname" . }}-snapshot-validation
      path: "/volumesnapshot"
    caBundle: {{ $ca.Cert | b64enc | quote }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 2
{{- end }}
