{{- if and .Values.controller.enabled .Values.controller.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaleway-csi.fullname" . }}-snapshot-validation
  labels:
    {{- include "scaleway-csi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "scaleway-csi.selectorLabels" . | nindent 4 }}
    app: {{ include "scaleway-csi.fullname" . }}-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
{{- end }}
