{{- define "environments-contents" -}}
RELEASE_NAME: {{ .Release.Name | b64enc }}
{{- range .Values.environments }}
{{ regexReplaceAll "\\W+" .name "_" | upper }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Helpers.fullname" . }}-env
  labels:
    {{- include "Helpers.labels" . | nindent 4 }}
type: Opaque
data: {{ include "environments-contents" . | nindent 2 }}
