networkPolicies:
  # Allow hubble-relay and hubble-ui to connect
  enabled: false

nodeConfig:
  # Enable Hubble gRPC service.
  enable-hubble: "true"
  # UNIX domain socket for Hubble server to listen to.
  hubble-socket-path: "/var/run/cilium/hubble.sock"
  # Capacity of the buffer to store recent events.
  hubble-event-buffer-capacity: "32767"
  # Address to expose Hubble metrics (e.g. ":7070"). Metrics server will be disabled if this
  # field is not set.
  hubble-metrics-server: ":9965"
  hubble-metrics-server-enable-tls: "false"
  # A space separated list of metrics to enable. See [0] for available metrics.
  #
  # https://github.com/cilium/hubble/blob/master/Documentation/metrics.md
  hubble-metrics:
    dns:query;ignoreAAAA
    drop
    flow
    flows-to-world:any-drop;port
    httpV2
    icmp
    port-distribution
    tcp
  enable-hubble-open-metrics: "false"
  hubble-export-file-max-size-mb: "10"
  hubble-export-file-max-backups: "5"
  # An additional address for Hubble server to listen to (e.g. ":4244").
  hubble-listen-address: ":4244"

cilium:
  hubble:
    enabled: true
    eventBufferCapacity: 32767
    metrics:
      enabled:
      - dns:query;ignoreAAAA
      - drop
      - flow
      - flows-to-world:any-drop;port
      - httpV2
      - icmp
      - port-distribution
      - tcp
    relay:
      enabled: true
    ui:
      enabled: true
    tls:
      auto:
        method: cronjob

  agent: false
  operator:
    enabled: false
  envoy:
    enabled: false
